name: Documentation Deploy

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - name: Build docs (if you have a docs build step)
        run: npm run docs:build || echo "No docs build script; skipping"
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
