name: Release Notes Automation

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get PR title
        id: prinfo
        run: |
          echo "::set-output name=title::$(jq -r .pull_request.title < $GITHUB_EVENT_PATH)"
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "Release ${{ github.run_number }}"
          body: |
            Merged PR: ${{ steps.prinfo.outputs.title }}
            See changes in this release.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
